title: 'CPT 363/365 HUB'
default_lang: en
author:
  name: 'John Appleseed'
  email: john@email.com
taxonomies:
  - category
  - tag
metadata:
  description: 'A short description of your course would go here'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
displaymenuentries:
  enabled: true
menu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'http://getgrav.org/'
icon:
  post: calendar-o
gitrepo:
  editlinklocation: none
  editlinkicon: github
  editlinktext: 'Edit this Page'
  edittreeurl: 'https://github.com/hibbitts-design/grav-skeleton-course-hub-site/edit/master/user/'
  editthemelinklocation: none
  editthemelinktext: 'Site Theme Files'
twittertimeline:
  enabled: false
  url: 'https://twitter.com/hibbittsdesign/lists/cpt-363'
  text: 'A Twitter List by @hibbittsdesign'
  height: 700
hidehomemenulink: false
cc_license:
  enabled: false
  type: ccby
