title: CPT 363/365 Hub
metadata:
    description: 'A short description of your course would go here'
displaymenuentries:
    enabled: true         # display of additional menu entries
menu:                     # menu entry for adding external sites/tools
    - text: Grav
      icon: arrow-circle-right
      url: http://getgrav.org/
icon:                     # default font awesome icons for preparation and post entries
    post: calendar-o
github:
    location: none         # menu | page | none
    icon: github
    tree: https://github.com/hibbitts-design/grav-skeleton-multi-course-pages-hub-site/edit/master/user/pages/
twittertimeline:
    enabled: false         # display of Twitter timeline on sidebar
    url: https://twitter.com/hibbittsdesign/lists/cpt-363
    widgetid: '684866063188676608'
